# Generated by Django 5.2.10 on 2026-01-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_manual_tags_document_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
