# Generated by Django 5.2.10 on 2026-01-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='audit_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='is_corrected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='manual_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
